# Change these first
owner: mrfryingpan # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Status Page
    url: https://status.ifry.fyi
    icon: https://static-00.iconduck.com/assets.00/statuspage-icon-512x376-dwgwn32f.png
    expectedStatusCodes:
      - 301
  - name: Bitwarden
    url: $SS_BW
    icon: https://images.saasworthy.com/bitwarden_32699_logo_1667563601_unbxr.png
    expectedStatusCodes:
      - 301
  - name: MessBot
    url: https://mess.ifry.fyi
    icon: https://cdn.prod.website-files.com/5f9072399b2640f14d6a2bf4/619442eb8b3fab3eda4c29eb_Author-Wumpus-Webflow.png
    expectedStatusCodes:
      - 301

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ifry.fyi
  # baseUrl: /your-repo-name
  theme: night
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.ifry.fyi
  introTitle: "**status.ifry.fyi** — status page, powered entirely by GitHub."
  introMessage: This status page uses **real-time** data from [GitHub repository](https://github.com/MrFryingPan/status) — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://ifry.fyi

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
