owner: mrfryingpan
repo: status

sites:
  - name: Status Page
    url: https://status.ifry.fyi
    icon: https://static-00.iconduck.com/assets.00/statuspage-icon-512x376-dwgwn32f.png
  - name: Bitwarden
    url: $SS_BW
    icon: https://images.saasworthy.com/bitwarden_32699_logo_1667563601_unbxr.png
  - name: MessBot
    url: https://mess.ifry.fyi
    icon: https://cdn.prod.website-files.com/5f9072399b2640f14d6a2bf4/619442eb8b3fab3eda4c29eb_Author-Wumpus-Webflow.png

status-website:
  cname: status.ifry.fyi
  theme: night
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.ifry.fyi
  introTitle: "**status.ifry.fyi** — status page, powered entirely by GitHub."
  introMessage: This status page uses **real-time** data from [GitHub repository](https://github.com/MrFryingPan/status) — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://ifry.fyi
i18n:
  footer: Made with &#128420, by [MrFryingPan](https://dsc.gg/mess).
